sym = {
    "dfrac": "frac",
    "$$": "",
    "{,}": ",",
    "\\circ": "∘",
    "\\ldots": "…",
    "\\dots": "…",

    "\\degree": "°",
    "\\deg": "°",

    "\\pm": "±",
    "\\mp": "∓",
    "\\times": "*",
    "\\div": "/",
    "\\cdot": "*",
    "\\left|": "abs(",
    "\\right|": ")",
    "\\infty": "∞",

    "\\sphericalangle": "∢",
    "\\angle": "∠",
    "\\parallel": "∥",
    "\\nparallel": "∦",
    "\\mid": "∣",
    "\\sim": "~",
    "\\propto": "∝",

    "\\neq": "≠",
    "\\equiv": "≡",
    "\\not\\equiv": "≢",
    "\\approx": "≈",
    "&=": "=",

    "\\mathbb{N}": "ℕ",
    "\\mathbb{Z}": "ℤ",
    "\\mathbb{Q}": "ℚ",
    "\\mathbb{R}": "ℝ",
    "\\mathbb{C}": "ℂ",
    "\\mathbb{P}": "ℙ",

    "\\subset": "⊂",
    "\\subseteq": "⊆",
    "\\cap": "∩",
    "\\cup": "∪",
    "\\varnothing": "∅",
    "\\notin": "∉",
    "\\setminus": "\\",
    "\\backslash": "\\",
    "\\forall": "∀",
    "\\exists": "∃",

    "\\neg": "¬",
    "\\and": "∧",
    "\\or": "∨",
}

greek = {
    "\\Alpha": "Α",
    "\\Beta": "Β",
    "\\Gamma": "Γ",
    "\\Delta": "Δ",
    "\\Epsilon": "Ε",
    "\\Zeta": "Ζ",
    "\\Eta": "Η",
    "\\Theta": "Θ",
    "\\Iota": "Ι",
    "\\Kappa": "Κ",
    "\\Lambda": "Λ",
    "\\Mu": "Μ",
    "\\Nu": "Ν",
    "\\Xi": "Ξ",
    "\\Omicron": "Ο",
    "\\Pi": "Π",
    "\\Rho": "Ρ",
    "\\Sigma": "Σ",
    "\\Tau": "Τ",
    "\\Upsilon": "Υ",
    "\\Phi": "Φ",
    "\\Chi": "Χ",
    "\\Psi": "Ψ",
    "\\Omega": "Ω",
    "\\alpha": "α",
    "\\beta": "β",
    "\\gamma": "γ",
    "\\delta": "δ",
    "\\epsilon": "ε",
    "\\varepsilon": "ε",
    "\\zeta": "ζ",
    "\\eta": "η",
    "\\theta": "θ",
    "\\iota": "ι",
    "\\kappa": "κ",
    "\\lambda": "λ",
    "\\mu": "μ",
    "\\nu": "ν",
    "\\xi": "ξ",
    "\\omicron": "ο",
    "\\pi": "π",
    "\\rho": "ρ",
    "\\sigma": "σ",
    "\\tau": "τ",
    "\\upsilon": "υ",
    "\\phi": "φ",
    "\\varphi": "φ",
    "\\chi": "χ",
    "\\psi": "ψ",
    "\\omega": "ω",

    "\\partial": "∂",
    "\\nabla": "∇"
}
